In [1]:
import gensim
import pandas as pd

In [2]:
df=pd.read_json(r"D:\pythonproject\Cell_Phones_and_Accessories_5.json",lines=True)
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A30TL5EWN6DFXT,120401325X,christina,"[0, 0]",They look good and stick good! I just don't li...,4,Looks Good,1400630400,"05 21, 2014"
1,ASY55RVNIL0UD,120401325X,emily l.,"[0, 0]",These stickers work like the review says they ...,5,Really great product.,1389657600,"01 14, 2014"
2,A2TMXE2AFO7ONB,120401325X,Erica,"[0, 0]",These are awesome and make my phone look so st...,5,LOVE LOVE LOVE,1403740800,"06 26, 2014"
3,AWJ0WZQYMYFQ4,120401325X,JM,"[4, 4]",Item arrived in great time and was in perfect ...,4,Cute!,1382313600,"10 21, 2013"
4,ATX7CZYFXI1KW,120401325X,patrice m rogoza,"[2, 3]","awesome! stays on, and looks great. can be use...",5,leopard home button sticker for iphone 4s,1359849600,"02 3, 2013"

In [3]:
df.shape

(194439, 9)

In [4]:
review_text = df.reviewText.apply(gensim.utils.simple_preprocess)

In [5]:
review_text

0         [they, look, good, and, stick, good, just, don...
1         [these, stickers, work, like, the, review, say...
2         [these, are, awesome, and, make, my, phone, lo...
3         [item, arrived, in, great, time, and, was, in,...
4         [awesome, stays, on, and, looks, great, can, b...
                                ...
194434    [works, great, just, like, my, original, one, ...
194435    [great, product, great, packaging, high, quali...
194436    [this, is, great, cable, just, as, good, as, t...
194437    [really, like, it, becasue, it, works, well, w...
194438    [product, as, described, have, wasted, lot, of...
Name: reviewText, Length: 194439, dtype: object

In [6]:
review_text.loc[0]

['they',
 'look',
 'good',
 'and',
 'stick',
 'good',
 'just',
 'don',
 'like',
 'the',
 'rounded',
 'shape',
 'because',
 'was',
 'always',
 'bumping',
 'it',
 'and',
 'siri',
 'kept',
 'popping',
 'up',
 'and',
 'it',
 'was',
 'irritating',
 'just',
 'won',
 'buy',
 'product',
 'like',
 'this',
 'again']

In [7]:
df.reviewText.loc[0]

"They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up and it was irritating. I just won't buy a product like this again"

In [8]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4,
)

In [9]:
model.build_vocab(review_text, progress_per=1000)

In [10]:
model.train(review_text, total_examples=model.corpus_count, epochs=model.epochs)

(61504579, 83868975)

In [11]:
model.wv.most_similar("bad")

[('terrible', 0.6727744340896606),
 ('shabby', 0.6657071709632874),
 ('horrible', 0.6058792471885681),
 ('good', 0.5863973498344421),
 ('okay', 0.5474215149879456),
 ('crappy', 0.5462179183959961),
 ('disappointing', 0.5363190174102783),
 ('awful', 0.5362839102745056),
 ('poor', 0.5180349946022034),
 ('upset', 0.515292227268219)]

In [12]:
model.wv.similarity(w1="cheap", w2="inexpensive")

np.float32(0.51948804)

In [13]:
model.wv.similarity(w1="great", w2="good")

np.float32(0.78893816)

In [14]:
model.wv.similarity(w1="good", w2="good")

np.float32(0.99999994)

In [17]:
model.wv.similarity(w1="sexy", w2="good")

np.float32(0.3157857)

In [18]:
df2=pd.read_json(r"D:\pythonproject\Sports_and_Outdoors_5.json",lines=True)
df2.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,AIXZKN4ACSKI,1881509818,David Briner,"[0, 0]",This came in on time and I am veru happy with ...,5,Woks very good,1390694400,"01 26, 2014"
1,A1L5P841VIO02V,1881509818,Jason A. Kramer,"[1, 1]",I had a factory Glock tool that I was using fo...,5,Works as well as the factory tool,1328140800,"02 2, 2012"
2,AB2W04NI4OEAD,1881509818,J. Fernald,"[2, 2]",If you don't have a 3/32 punch or would like t...,4,"It's a punch, that's all.",1330387200,"02 28, 2012"
3,A148SVSWKTJKU6,1881509818,"Jusitn A. Watts ""Maverick9614""","[0, 0]",This works no better than any 3/32 punch you w...,4,It's a punch with a Glock logo.,1328400000,"02 5, 2012"
4,AAAWJ6LW9WMOO,1881509818,Material Man,"[0, 0]",I purchased this thinking maybe I need a speci...,4,"Ok,tool does what a regular punch does.",1366675200,"04 23, 2013"

In [20]:
review_text2 = df2.reviewText.apply(gensim.utils.simple_preprocess)
review_text2

0         [this, came, in, on, time, and, am, veru, happ...
1         [had, factory, glock, tool, that, was, using, ...
2         [if, you, don, have, punch, or, would, like, t...
3         [this, works, no, better, than, any, punch, yo...
4         [purchased, this, thinking, maybe, need, speci...
                                ...
296332    [this, is, water, bottle, done, right, it, is,...
296333    [if, you, re, looking, for, an, insulated, wat...
296334    [this, hydracentials, sporty, oz, double, insu...
296335    [as, usual, received, this, item, free, in, ex...
296336    [hydracentials, insulated, oz, water, bottle, ...
Name: reviewText, Length: 296337, dtype: object

In [21]:
review_text2.loc[0]

['this',
 'came',
 'in',
 'on',
 'time',
 'and',
 'am',
 'veru',
 'happy',
 'with',
 'it',
 'haved',
 'used',
 'it',
 'already',
 'and',
 'it',
 'makes',
 'taking',
 'out',
 'the',
 'pins',
 'in',
 'my',
 'glock',
 'very',
 'easy']

In [22]:
df2.reviewText.loc[0]

'This came in on time and I am veru happy with it, I haved used it already and it makes taking out the pins in my glock 32 very easy'

In [23]:
model2 = gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4,
)

In [24]:
model2.build_vocab(review_text2, progress_per=1000)

In [26]:
model2.train(review_text2, total_examples=model.corpus_count, epochs=model.epochs)

(91340071, 121496535)

In [27]:
model2.wv.most_similar("awful")

[('horrible', 0.7952544689178467),
 ('terrible', 0.7774960994720459),
 ('ugly', 0.6351563334465027),
 ('atrocious', 0.6175506711006165),
 ('unpleasant', 0.6138004064559937),
 ('horrendous', 0.6060967445373535),
 ('pathetic', 0.5736279487609863),
 ('nightmare', 0.5732288360595703),
 ('funny', 0.5718263983726501),
 ('poor', 0.5628005266189575)]

In [29]:
model2.wv.similarity(w1="good", w2="great")

np.float32(0.78648347)

In [30]:
model2.wv.similarity(w1="slow", w2="steady")

np.float32(0.3591932)